version: 2

jobs:
  build:
    docker:
      - image: elixir:1.6.5
    steps:
      - checkout
      - run: mix do local.rebar --force, local.hex --force
      - run: curl https://static.rust-lang.org/rustup.sh | sh
      - run: rustup install beta
      - run: rustup install nightly
  stable:
    docker:
      - image: elixir:1.6.5
    steps:
      - run: cargo test
      - run: cd rustler_tests && mix test
  beta:
    docker:
      - image: elixir:1.6.5
    steps:
      - run: rustup override set beta
      - run: cargo test
      - run: cd rustler_tests && mix test
  nightly:
    docker:
      - image: elixir:1.6.5
    steps:
      - run: rustup override set nightly
      - run: cargo test
      - run: cd rustler_tests && mix test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - stable:
          requires:
            - build
      - beta:
          requires:
            - build
      - nightly:
          requires:
            - build
